server:
  port: 8000

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 35672
    username: boge
    password: boge14@Level5
    virtual-host: /wddserver

octopus:
  message:
    # agent boot up default common exchange
    init_exchange: InitExchange
    # server will send message to agent using this common queue
    init_to_server: InitToServer
    # agent boot up default common exchange routing key
    init_to_server_key: InitToServerKey
    # server will receive message from agent using this common queue
    init_from_server: InitFromServer
    # agent boot up default common exchange routing key
    init_from_server_key: InitFromServerKey
    # initialization register time out (unit ms) default is 5 min
    init_ttl: "3000000"